local_costmap:
#   global_frame: /odom
   global_frame: /odom_combined
   robot_base_frame: /base_footprint
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap

  #  #膨胀半径，扩展在碰撞区域以外的代价区域，使得机器人规划路径避开障碍物，local可以设置的比global小
  #  inflation_radius: 0.07
  #  #代价比例系数，越大则代价值越小
  #  cost_scaling_factor: 5.0 # default 5.0

   plugins:
     - {name: static_layer,        type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
     - {name: virtualWall_layer,   type: "costmap_2d::VirtualWallLayer"}
     - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
