base_frame: "base_footprint" 
odom_frame: "odom_combined"  
map_update_interval: 0.01 
maxUrange: 8.0 
maxRange: 10.0 
sigma: 0.05 
kernelSize: 3 
lstep: 0.05 
astep: 0.05 
iterations: 5 
lsigma: 0.075 
ogain: 3.0 
lskip: 0 
minimumScore: 30 
srr: 0.01 
srt: 0.02 
str: 0.01 
stt: 0.02 
linearUpdate: 0.05 
angularUpdate: 0.0436 
temporalUpdate: -1.0 
resampleThreshold: 0.5 
particles: 50 
xmin: -1.0 
ymin: -1.0
xmax: 1.0
ymax: 1.0

delta: 0.05 
llsamplerange: 0.01 
llsamplestep: 0.01 
lasamplerange: 0.005 
lasamplestep: 0.005 











