ProductNUM: EAI_LEO_A02_L102900101_G1_321648742
Version: LEO-sv1.5hv1.1
base_type: 1  # CIRCLE = 0 SQUARE = 1
base_radius_mm: 0  # the radius of platform
distance_between_wheels_mm: 282
chassis_pos0_x: 189
chassis_pos0_y: 225
chassis_pos1_x: 189
chassis_pos1_y: -225
chassis_pos2_x: -189
chassis_pos2_y: -225
chassis_pos3_x: -189
chassis_pos3_y: 225
base_snoar_num: 2
base_snoars0_x: 182
base_snoars0_y: -74
base_snoars0_z: 134
base_snoars0_w: 0  # anti clockwise angle to center degree
base_snoars1_x: 182
base_snoars1_y: 74
base_snoars1_z: 134
base_snoars1_w: 0
base_snoars2_x: 0
base_snoars2_y: 0
base_snoars2_z: 0
base_snoars2_w: 0
base_snoars3_x: 0
base_snoars3_y: 0
base_snoars3_z: 0
base_snoars3_w: 0
base_snoars4_x: 0
base_snoars4_y: 0
base_snoars4_z: 0
base_snoars4_w: 0
base_snoars5_x: 0
base_snoars5_y: 0
base_snoars5_z: 0
base_snoars5_w: 0
base_snoars6_x: 0
base_snoars6_y: 0
base_snoars6_z: 0
base_snoars6_w: 0
base_snoars7_x: 0
base_snoars7_y: 0
base_snoars7_z: 0
base_snoars7_w: 0
base_snoars8_x: 0
base_snoars8_y: 0
base_snoars8_z: 0
base_snoars8_w: 0
base_snoars9_x: 0
base_snoars9_y: 0
base_snoars9_z: 0
base_snoars9_w: 0
base_bumper_num: 0
base_bumpers0_x: 0
base_bumpers0_y: 0
base_bumpers0_z: 0
base_bumpers0_w: 0
base_bumpers1_x: 0
base_bumpers1_y: 0
base_bumpers1_z: 0
base_bumpers1_w: 0
base_bumpers2_x: 0
base_bumpers2_y: 0
base_bumpers2_z: 0
base_bumpers2_w: 0
base_bumpers3_x: 0
base_bumpers3_y: 0
base_bumpers3_z: 0
base_bumpers3_w: 0
base_drop_num: 0
base_drops0_x: 0
base_drops0_y: 0
base_drops0_z: 0
base_drops0_w: 0
base_drops1_x: 0
base_drops1_y: 0
base_drops1_z: 0
base_drops1_w: 0
base_drops2_x: 0
base_drops2_y: 0
base_drops2_z: 0
base_drops2_w: 0
base_drops3_x: 0
base_drops3_y: 0
base_drops3_z: 0
base_drops3_w: 0
base_lidar_num: 1
base_lidar0_x: 120
base_lidar0_y: 0
base_lidar0_z: 112
base_lidar0_w: 0
base_lidar1_x: 0
base_lidar1_y: 0
base_lidar1_z: 0
base_lidar1_w: 0
base_camera_x: 0
base_camera_y: 0
base_camera_z: 0
base_camera_w: 0